name: Coverage
on: push
jobs:
  genCoverage: 
    name: Generate coverage
    - uses: actions/checkout@master
    - run: cd ./tasks-fe && jest --ci --coverage && codecov
    jobs:
      uploadCoverage:
        name: Upload coverage to Codecov
        - uses: codecov/codecov-action@v2

