name: Coverage
on: push
jobs:
  generateCoverage:
    name: Generate coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ./tasks-fe && npm install
    - run: cd ./tasks-fe && npm test -- --coverage --reporter=lcov
  uploadCoverage:
    name: Upload coverage to Codecov
    runs-on: ubuntu-latest
    environment: dev
    needs: generateCoverage
    steps:
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          directory: ./tasks-fe/coverage/
          flags: FE