name: Coverage
on: push
jobs:
  run:
    name: Generate coverage
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [16.13.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ./tasks-fe && npm install
    - run: cd ./tasks-fe && npm test -- --coverage --reporter=lcov
    - run: cd ./tasks-fe/coverage && ls
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        root_dir: ./tasks-fe/
        directory: ./coverage/
        files: ./clover.xml,./coverage-final.json
        flags: FE