name: Coverage
on: push
jobs:
  generateCoverage:
    name: Generate coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cd ./tasks-fe && jest --ci --coverage && codecov
  uploadCoverage:
    name: Upload coverage to Codecov
    runs-on: ubuntu-latest
    needs: generateCoverage
    steps:
      - uses: codecov/codecov-action@v2